### PR TITLE
Elm 0.19

### PR DESCRIPTION
**Pull request by domenkozar**
Including all other fixes maintained by @FPtje fork. Testing/feedback welcome.

cc @krisajenkins

### CODE REVIEW

**Comment by szg251** [comment]
@domenkozar I fixed the tests on this PR: https://github.com/hercules-ci/elm-export/pull/1

**Comment by domenkozar** [comment]
Thank you.

**Comment by seanhess** [comment]
Will this PR be merged and the package republished soon? How can I help?

**Comment by FranklinChen** [comment]
Maybe someone should take over this package.

**Comment by k-bx** [comment]
No idea why I forgot to check out GitHub issues to find already present forks, but anyways I've made another fork. I've replaced elm-export with elm-bridge, but overall code quality is pretty alpha.

https://github.com/k-bx/servant-elm

Example CRUD I'm using as a basis: https://github.com/k-bx/servant-elm-generically

**Comment by k-bx** [comment]
@domenkozar would you mind making a request to take over the package and move it to your repo? Would really help avoid situations like the one I've had

**Comment by domenkozar** [comment]
As servant-elm moved to elm-bridge I'm no longer interested in this work (although we still use it, but will transition away).

**Pull request closed without merging**
